title: Documentación de Iván
description: Primeros pasos utilizando Github Pages y la plantilla "just-the-docs"
theme: just-the-docs
color_scheme: dark

url: https://ivanpodo.github.io/ivanpodo

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/test-img.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"

# Some standard callouts. 
# To change its opacity 'opacity: 0.3' (def: 0.2)

callouts:
  warning:
    title: Warning
    color: red

  tips:
    title: Tips
    color: yellow
  
  info:
    title: Info
    color: blue

  good:
    title: Good
    color: green
